import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import React, { ReactNode } from "react";

// Import CSS files
import "@/assets/libs/tobii/css/tobii.min.css";
import "@/assets/libs/tiny-slider/tiny-slider.css";
import "@/assets/libs/choices.js/public/assets/styles/choices.min.css";
import "@/assets/libs/@iconscout/unicons/css/line.css";
import "@/assets/libs/@mdi/font/css/materialdesignicons.min.css";
import "@/assets/css/tailwind.min.css";
import "@/assets/css/style.css";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <>

      <html lang="en" className="light scroll-smooth">
        <body className={`${inter.className} dark:bg-slate-900`}>{children}</body>
      </html>
    </>
  );
};

export default RootLayout;
