import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/assets/libs/tobii/css/tobii.min.css"
import "@/assets/libs/tiny-slider/tiny-slider.css"
import "@/assets/libs/choices.js/public/assets/styles/choices.min.css"
import "@/assets/libs/@iconscout/unicons/css/line.css"
import "@/assets/libs/@mdi/font/css/materialdesignicons.min.css"
import "@/assets/css/tailwind.min.css"
import "@/assets/css/style.css"

import "@/assets/libs/tobii/js/tobii.min.js"
import "@/assets/libs/feather-icons/feather.min"
// import "@/assets/js/plugins.init.js"
// import "@/assets/js/app"
// import "@/assets/libs/tiny-slider/min/tiny-slider"
// import "@/assets/libs/choices.js/public/assets/scripts/choices.min"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light scroll-smooth">
      <body className={`dark:bg-slate-900 ${inter.className}`}>{children}</body>
    </html>
  );
}
